FORMAT: 1A
HOST: https://push-server-api.logbk.net/v1

# LogPush Server API

## /delivery

### POST

全体か指定したセグメント、もしくは特定のデバイスに向けてメッセージを配信します。
配信はAPIコール時に開始されます。

`message` (オプション)には送信するメッセージを80文字以内で指定します。

`badge` (オプション) にはバッジを非負整数で指定します。
指定しなかった場合、バッジの状態は変更されません。
0を指定した場合、バッジは非表示になります。
1以上を指定した場合、指定した数がバッジに表示されます。
`badge` は現在 iOS のみに対応しています。

`customField` (オプション) には JSON object として正しい文字列をUTF-8で255バイト以内で指定します。
iOS の場合は customField に `aps` フィールドを含んだ JSON を指定することで
LogPush が生成する `aps` フィールドを上書きすることができます。
`aps` フィールドの詳細については
[Local and Remote Notification Programming Guide, The Remote Notification Payload](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW2)
をご参照ください。

`launchUrl` (オプション) には起動URL(通知をタップしたときに設定したURL)を指定します。
::: note
launchUrlオプションは [LogPushプレミアム](https://logpush.groovehq.com/knowledge_base/topics/logpushpuremiamunituite) でのみ提供される機能です。
:::


`ratePerSecond` (オプション) には送信速度制限(通/秒数)を指定します。
指定しない場合には制限されません。
内部では1000通ごとにまとめて送信を処理しています。
速度制限はこのまとまりの間隔を調整します。
たとえば送信速度制限を100通/秒数に指定した時、1通目から1000通目は即時に送信が開始され、1001通目から2000通目は10秒後に開始されます。

`isTest` (オプション。デフォルト false) に true を指定すると、開発環境のデバイスにのみ配信されます。

`segmentId`/`devices` (オプション) はどちらか一方を指定のみ指定することができます。また、どちらも指定しないということもできます。
配信したいセグメントがある場合には`segmentId`にそのセグメントのIDを指定します。
配信したいデバイストークンのリストがある場合には`devices`にそのデバイストークンのリスト（tokens）と環境（environment）、プラットフォーム（platform）を指定します。
* devices
  * environment: 開発の場合は `development`。本番の場合は `production`。
  * platform: `Android` または `iOS`
  * tokens:
    Android の場合は GCM の registration token、iOS の場合は APNs の device token (16進表記)のリスト。tokensは1リクエストにつき最大1000件まで指定できます。

全体へ配信する場合には `segmentId`と`devices`のどちらも指定しません。

::: note
segmentIdオプションとdevicesオプションは [LogPushプレミアム](https://logpush.groovehq.com/knowledge_base/topics/logpushpuremiamunituite) でのみ提供される機能です。
:::

+ Request Simple request
    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "message": "Hello"
            }

+ Request With options
    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "message": "Hello",
              "segmentId": "0123456789",
              "customField": "{\"key\":\"value\"}",
              "badge": 123,
              "launchUrl": "http://example.com/",
              "ratePerSecond": 1000
            }

+ Response 200

        {
          "apiCallId": "2345678901"
        }

+ Request With devices options
    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "message": "Hello",
              "devices": [
                {
                  "platform": "iOS",
                  "environment": "production",
                  "tokens": [
                    "F49FF5AF2ECCDA9C63782B49C1A28CB5...",
                    "629AF3C693EC2F123F11559615BB690E..."
                  ]
                },
                {
                  "platform": "Android",
                  "environment": "production",
                  "tokens": [
                    "APA91bH9-m-MHPlU8a1L37Idcy7abWmT3vUNQD..."
                  ]
                }
              ],
              "customField": "{\"key\":\"value\"}",
              "badge": 123,
              "launchUrl": "http://example.com/",
              "ratePerSecond": 1000
            }

+ Response 200

        {
          "apiCallId": "2345678901"
        }

+ Request Test delivery
    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "message": "Hello",
              "isTest": true
            }

+ Request iOS silent push

    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "customField": "{\"aps\": {\"sound\": null, \"content-available\": 1}}",
              "ratePerSecond": 1000
            }

+ Response 200

        {
          "apiCallId": "2345678901"
        }

## /tag

### POST

特定のデバイスやデバイス集合を対象にして、タグの追加、更新、削除を行います。

device と tagQuery はどちらか一方のみを指定します。

* device: 合致したデバイスを対象にして、タグを追加、更新、削除します。
  * environment: 開発の場合は `development`。本番の場合は `production`。
  * platform: `Android` または `iOS`
  * token:
    Android の場合は GCM の registration token。
    iOS の場合は APNs の device token (16進表記)。
* tagQuery: タグ名とタグ値が該当したデバイス集合を対象にして、タグを追加、更新、削除します。
  最大100までのデバイスを1リクエストで更新します。
  100より多くのデバイスが該当した場合、タグは追加、更新、削除されません。
  * name: タグ名
  * value: 検索文字列
    (現在は文字列一致のみが扱えます。数値のタグは文字列で検索可能です。日時のタグは検索対象にできません。)
* tags: 登録または更新するタグの一覧。最大100個。
  * name: タグ名
  * value: タグ値
* deleteTagNames: 削除するタグの一覧。最大100個。

タグ名は `[a-zA-Z0-9_]` からなる1文字以上64文字以下の文字列で指定します。

タグ値は

* 文字列
* `{"dateTime": 1970年1月1日 00:00:00 UTCからのミリ秒数}` 形式の JSON オブジェクト

のいずれかで指定します。

+ Request device

    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "device": {
                "environment": "production",
                "platform": "Android",
                "token": "APA91bH9-m-MHPlU8a1L37Idcy7abWmT3vUNQD..."
              },
              "tags": [
                {"name": "age", "value": "21"},
                {"name": "lastClicked", "value": {"dateTime": 1437467779198}}
              ],
              "deleteTagNames": ["weight"]
            }

+ Request tagQuery

    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "tagQuery": {
                "name": "userId",
                "value": "123"
              },
              "tags": [
                {"name": "age", "value": "21"},
                {"name": "lastClicked", "value": {"dateTime": 1437467779198}}
              ],
              "deleteTagNames": ["weight"]
            }

+ Response 200

        {
          "apiCallId": "123456789012345"
        }
