FORMAT: 1A
HOST: https://push-server-api.logbk.net/v1

# LogPush Server API

## /delivery

### POST

指定したセグメント、あるいは全体に向けてメッセージを配信します。
配信はAPIコール時に開始されます。

`segmentId` と `customField` はオプショナルです。
全体へ配信する場合には `segmentId` を指定しません。
`customField` には JSON object として正しい文字列を指定します。


+ Request
    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "message": "Hello",
              "segmentId": "0123456789",
              "customField": "{\"key\":\"value\"}"
            }

+ Response 200

        {
          "apiCallId": "2345678901"
        }
