FORMAT: 1A
HOST: https://push-server-api.logbk.net/v1

# LogPush Server API

## /delivery

### POST

指定したセグメント、あるいは全体に向けてメッセージを配信します。
配信はAPIコール時に開始されます。

`message` には送信するメッセージを80文字以内で指定します。

`segmentId` (オプション) には配信する対象のセグメントのIDを指定します。
全体へ配信する場合には `segmentId` を指定しません。

`customField` (オプション) には JSON object として正しい文字列をUTF-8で255バイト以内で指定します。

`ratePerSecond` (オプション) には送信速度制限(通/秒数)を指定します。
指定しない場合には制限されません。
内部では1000件ごとにまとめて送信を処理しています。
速度制限はこのまとまりの間隔を調整します。
たとえば送信速度制限を100通/秒数に指定した時、1件目から1000件目は即時に送信が開始され、1001件目から2000件目は10秒後に開始されます。


+ Request
    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "message": "Hello",
              "segmentId": "0123456789",
              "customField": "{\"key\":\"value\"}",
              "ratePerSecond": 1000
            }

+ Response 200

        {
          "apiCallId": "2345678901"
        }

## /tag

### POST

特定のデバイスやデバイス集合を対象にして、タグの追加、更新、削除を行います。

device と tagQuery はどちらか一方のみを指定します。

* device: 合致したデバイスを対象にして、タグを追加、更新、削除します。
  * environment: 開発の場合は `development`。本番の場合は `production`。
  * platform: `Android` または `iOS`
  * token:
    Android の場合は GCM の registration token。
    iOS の場合は APNs の device token (16進表記)。
* tagQuery: タグ名とタグ値が該当したデバイス集合を対象にして、タグを追加、更新、削除します。
  最大100までのデバイスを1リクエストで更新します。
  100より多くのデバイスが該当した場合、タグは追加、更新、削除されません。
  * name: タグ名
  * value: 検索文字列
    (現在は文字列一致のみが扱えます。数値のタグは文字列で検索可能です。日時のタグは検索対象にできません。)
* tags: 登録または更新するタグの一覧。最大100個。
  * name: タグ名
  * value: タグ値
* deleteTagNames: 削除するタグの一覧。最大100個。

タグ名は `[a-zA-Z0-9_]` からなる1文字以上64文字以下の文字列で指定します。

タグ値は

* 文字列
* `{"dateTime": 1970年1月1日 00:00:00 UTCからのミリ秒数}` 形式の JSON オブジェクト

のいずれかで指定します。

+ Request device

    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "device": {
                "environment": "production",
                "platform": "Android",
                "token": "APA91bH9-m-MHPlU8a1L37Idcy7abWmT3vUNQD..."
              },
              "tags": [
                {"name": "age", "value": "21"},
                {"name": "lastClicked", "value": {"dateTime": 1437467779198}}
              ],
              "deleteTagNames": ["weight"]
            }

+ Request tagQuery

    + Headers

            X-Api-Key: API_KEY

    + Body

            {
              "tagQuery": {
                "name": "userId",
                "value": "123"
              },
              "tags": [
                {"name": "age", "value": "21"},
                {"name": "lastClicked", "value": {"dateTime": 1437467779198}}
              ],
              "deleteTagNames": ["weight"]
            }

+ Response 200

        {
          "apiCallId": "123456789012345"
        }
