version: 2
jobs:
    build:
        docker:
            - image: "circleci/node:8.11.2"
              environment:
                  TZ: "/usr/share/zoneinfo/Asia/Tokyo"
        branches:
            only:
                - master
        steps:
            - checkout
            - restore_cache:
                key: dependencies-{{ checksum "package.json" }}
            - run:
                name: install
                command: npm install
            - save_cache:
                key: dependencies-{{ checksum "package.json" }}
                paths:
                    - "./node_modules"
            - run:
                name: deploy
                command: ./scripts/deploy.sh
