version: 2
jobs:
    build:
        docker:
            - image: "circleci/node:8.11.2"
              environment:
                  TZ: "/usr/share/zoneinfo/Asia/Tokyo"
        steps:
            - checkout
            - restore_cache:
                key: dependencies-{{ checksum "package.json" }}
            - run:
                name: install
                command: npm install
            - save_cache:
                key: dependencies-{{ checksum "package.json" }}
                paths:
                    - "./node_modules"
            - run:
                name: build
                command: ./scripts/build.sh
            - store_artifacts:
                path: "./target"
            - persist_to_workspace:
                root: "."
                paths:
                    - "target"
    deploy:
        docker:
            - image: "circleci/node:8.11.2"
              environment:
                  TZ: "/usr/share/zoneinfo/Asia/Tokyo"
        steps:
            - checkout
            - attach_workspace:
                at: "."
            - run:
                name: deploy
                command: ./scripts/deploy.sh
workflows:
    version: 2
    build_deploy_workflow:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - master
